# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('book_author', models.CharField(default='', editable=False, max_length=255)),
                ('book_isbn_no', models.CharField(default='SOME STRING', max_length=255)),
                ('book_pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('customer_name_surname', models.CharField(max_length=255)),
                ('customer_mail', models.EmailField(max_length=254)),
                ('customer_adress', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.Customer'),
        ),
    ]
